export { ProductCard } from "./ui/productCard/ProductCard"
export { ProductGrid } from "./ui/ProductGrid"
export { ProductCardSkeleton } from "./ui/productCard/ProductCardSkeleton"
export { ProductGridSkeleton } from "@/4_entities/product/ui/ProductGridSkeleton"

export type { Product, ProductDetail } from "./types/product.frontend"
export { useProductListQuery } from "./api/product.list"
export { useProductDetailQuery } from "./api/product.detail"
export { ProductDetailGallery } from "./ui/ProductDetailGallery"
export { ProductAvailability } from "../../2_pages/product-detail-page/ui/ProductAvailability"
