import type { ProductBackend } from "@/4_entities/product/types/product.backend"
import type { ProductDetailBackend } from "@/4_entities/product/types/product.backend"

const productsList: ProductBackend[] = [
  {
    id: "PLC_001",
    condition: "New",
    onStock: true,
    onStockQuantity: 15,
    previewImageUrl: "/assets/img/mock/1.jpg",
    previewImageAlt: "Контроллер Siemens S7-1200 PLC",
    brand: "Siemens",
    name: "SIMATIC S7-1200 CPU 1214C",
    deliveryTime: 3,
    price: 485.5,
    productCode: "6ES7214-1AG40-0XB0",
  },
  {
    id: "DRV_002",
    condition: "New",
    onStock: true,
    onStockQuantity: 8,
    previewImageUrl: "/assets/img/mock/2.jpeg",
    previewImageAlt: "Преобразователь частоты Schneider Altivar",
    brand: "Schneider Electric",
    name: "Altivar 320 VFD - 5.5kW",
    deliveryTime: 5,
    price: 1250.0,
    productCode: "ATV320U55N4B",
  },
  {
    id: "HMI_003",
    condition: "Used",
    onStock: true,
    onStockQuantity: 2,
    previewImageUrl: "/assets/img/mock/3.jpg",
    previewImageAlt: "Сенсорная панель Siemens HMI",
    brand: "Siemens",
    name: "SIMATIC HMI TP700 Comfort Panel",
    deliveryTime: 4,
    price: 1890.75,
    productCode: "6AV2124-0GC13-0AX0",
  },
  {
    id: "SEN_004",
    condition: "New",
    onStock: false,
    onStockQuantity: 0,
    previewImageUrl: "/assets/img/mock/4.png",
    previewImageAlt: "Индуктивный датчик приближения",
    brand: "SICK",
    name: "Индуктивный датчик приближения IME series",
    deliveryTime: 7,
    price: 89.95,
    productCode: "IME12-04NPSZW2S",
  },
  {
    id: "MOT_005",
    condition: "New",
    onStock: true,
    onStockQuantity: 25,
    previewImageUrl: "/assets/img/mock/5.webp",
    previewImageAlt: "Электродвигатель ABB",
    brand: "ABB",
    name: "Электродвигатель IE3 - 7.5kW",
    deliveryTime: 10,
    price: 875.3,
    productCode: "M3BP160MLC4",
  },
  {
    id: "CNT_006",
    condition: "Used",
    onStock: true,
    onStockQuantity: 1,
    previewImageUrl: "/assets/img/mock/6.jpg",
    previewImageAlt: "Контроллер Allen Bradley PLC",
    brand: "Rockwell Automation",
    name: "ControlLogix 5570 Controller",
    deliveryTime: 5,
    price: 3250.0,
    productCode: "1756-L71",
  },
  {
    id: "PWR_007",
    condition: "New",
    onStock: true,
    onStockQuantity: 12,
    previewImageUrl: "/assets/img/mock/6.jpg",
    previewImageAlt: "Блок питания Siemens",
    brand: "Siemens",
    name: "SITOP PSU100S 20A Блок питания",
    deliveryTime: 2,
    price: 245.8,
    productCode: "6EP1336-3BA10",
  },
  {
    id: "RBT_008",
    condition: "New",
    onStock: false,
    onStockQuantity: 0,
    previewImageUrl: "/assets/img/mock/8.jpeg",
    previewImageAlt: "Промышленный робот Fanuc",
    brand: "Fanuc",
    name: "LR Mate 200iD Промышленный робот",
    deliveryTime: 30,
    price: 28500.0,
    productCode: "LR-200ID-7C",
  },
  {
    id: "SWT_009",
    condition: "Used",
    onStock: true,
    onStockQuantity: 3,
    previewImageUrl: "/assets/img/mock/9.webp",
    previewImageAlt: "Промышленный коммутатор Cisco",
    brand: "Cisco",
    name: "IE-2000 Промышленный коммутатор",
    deliveryTime: 3,
    price: 1875.4,
    productCode: "IE-2000-8TC",
  },
  {
    id: "SCA_010",
    condition: "New",
    onStock: true,
    onStockQuantity: 6,
    previewImageUrl: "/assets/img/mock/10.webp",
    previewImageAlt: "SCADA система Siemens",
    brand: "Siemens",
    name: "SIMATIC WinCC SCADA v8.0",
    deliveryTime: 1,
    price: 4560.0,
    productCode: "6AV6381-2BH07-0AV0",
  },
  {
    id: "PLC_001",
    condition: "New",
    onStock: true,
    onStockQuantity: 15,
    previewImageUrl: "/assets/img/mock/1.jpg",
    previewImageAlt: "Контроллер Siemens S7-1200 PLC",
    brand: "Siemens",
    name: "SIMATIC S7-1200 CPU 1214C",
    deliveryTime: 3,
    price: 485.5,
    productCode: "6ES7214-1AG40-0XB0",
  },
  {
    id: "DRV_002",
    condition: "New",
    onStock: true,
    onStockQuantity: 8,
    previewImageUrl: "/assets/img/mock/2.jpeg",
    previewImageAlt: "Преобразователь частоты Schneider Altivar",
    brand: "Schneider Electric",
    name: "Altivar 320 VFD - 5.5kW",
    deliveryTime: 5,
    price: 1250.0,
    productCode: "ATV320U55N4B",
  },
  {
    id: "HMI_003",
    condition: "Used",
    onStock: true,
    onStockQuantity: 2,
    previewImageUrl: "/assets/img/mock/3.jpg",
    previewImageAlt: "Сенсорная панель Siemens HMI",
    brand: "Siemens",
    name: "SIMATIC HMI TP700 Comfort Panel",
    deliveryTime: 4,
    price: 1890.75,
    productCode: "6AV2124-0GC13-0AX0",
  },
  {
    id: "SEN_004",
    condition: "New",
    onStock: false,
    onStockQuantity: 0,
    previewImageUrl: "/assets/img/mock/4.png",
    previewImageAlt: "Индуктивный датчик приближения",
    brand: "SICK",
    name: "Индуктивный датчик приближения IME series",
    deliveryTime: 7,
    price: 89.95,
    productCode: "IME12-04NPSZW2S",
  },
  {
    id: "MOT_005",
    condition: "New",
    onStock: true,
    onStockQuantity: 25,
    previewImageUrl: "/assets/img/mock/5.webp",
    previewImageAlt: "Электродвигатель ABB",
    brand: "ABB",
    name: "Электродвигатель IE3 - 7.5kW",
    deliveryTime: 10,
    price: 875.3,
    productCode: "M3BP160MLC4",
  },
  {
    id: "CNT_006",
    condition: "Used",
    onStock: true,
    onStockQuantity: 1,
    previewImageUrl: "/assets/img/mock/6.jpg",
    previewImageAlt: "Контроллер Allen Bradley PLC",
    brand: "Rockwell Automation",
    name: "ControlLogix 5570 Controller",
    deliveryTime: 5,
    price: 3250.0,
    productCode: "1756-L71",
  },
  {
    id: "PWR_007",
    condition: "New",
    onStock: true,
    onStockQuantity: 12,
    previewImageUrl: "/assets/img/mock/6.jpg",
    previewImageAlt: "Блок питания Siemens",
    brand: "Siemens",
    name: "SITOP PSU100S 20A Блок питания",
    deliveryTime: 2,
    price: 245.8,
    productCode: "6EP1336-3BA10",
  },
  {
    id: "RBT_008",
    condition: "New",
    onStock: false,
    onStockQuantity: 0,
    previewImageUrl: "/assets/img/mock/8.jpeg",
    previewImageAlt: "Промышленный робот Fanuc",
    brand: "Fanuc",
    name: "LR Mate 200iD Промышленный робот",
    deliveryTime: 30,
    price: 28500.0,
    productCode: "LR-200ID-7C",
  },
  {
    id: "SWT_009",
    condition: "Used",
    onStock: true,
    onStockQuantity: 3,
    previewImageUrl: "/assets/img/mock/9.webp",
    previewImageAlt: "Промышленный коммутатор Cisco",
    brand: "Cisco",
    name: "IE-2000 Промышленный коммутатор",
    deliveryTime: 3,
    price: 1875.4,
    productCode: "IE-2000-8TC",
  },
  {
    id: "SCA_010",
    condition: "New",
    onStock: true,
    onStockQuantity: 6,
    previewImageUrl: "/assets/img/mock/10.webp",
    previewImageAlt: "SCADA система Siemens",
    brand: "Siemens",
    name: "SIMATIC WinCC SCADA v8.0",
    deliveryTime: 1,
    price: 4560.0,
    productCode: "6AV6381-2BH07-0AV0",
  },
]

const ProductsDetailList: ProductDetailBackend[] = [
  {
    id: "PLC_001",
    condition: "New",
    onStock: true,
    onStockQuantity: 15,
    previewImageUrl: "/assets/mock/img/siemens.jpeg",
    previewImageAlt: "Контроллер Siemens S7-1200 PLC",
    brand: "Siemens",
    name: "SIMATIC S7-1200 CPU 1214C",
    deliveryTime: 3,
    price: 485.5,
    description:
      "Компактный ПЛК для базовых и расширенных задач автоматизации. Оснащен интегрированным интерфейсом PROFINET, 4 высокоскоростными счетчиками и возможностью расширения до 3 сигнальных модулей. Идеально подходит для малых и средних приложений с 14 цифровыми входами и 10 цифровыми выходами.",
    images: [
      "https://images.unsplash.com/photo-1581091226033-d5c48150dbaa",
      "https://images.unsplash.com/photo-1581092335871-5d9e0c2d0a3b",
    ],
    productCode: "6ES7214-1AG40-0XB0",
    datasheet: "https://www.siemens.com/s7-1200-cpu1214c-datasheet.pdf",
    seo: {
      title: "Siemens SIMATIC S7-1200 CPU 1214C | Компактный ПЛК контроллер",
      description:
        "Компактный программируемый логический контроллер с интегрированным PROFINET для малых и средних промышленных приложений автоматизации.",
      keywords: [
        "ПЛК Siemens",
        "S7-1200",
        "6ES7214-1AG40-0XB0",
        "компактный ПЛК",
        "промышленный контроллер",
        "автоматизация",
      ],
    },
  },
  {
    id: "DRV_002",
    condition: "New",
    onStock: true,
    onStockQuantity: 8,
    previewImageUrl:
      "https://images.unsplash.com/photo-1581092335871-5d9e0c2d0a3b",
    previewImageAlt: "Преобразователь частоты Schneider Altivar",
    brand: "Schneider Electric",
    name: "Altivar 320 VFD - 5.5kW",
    deliveryTime: 5,
    price: 1250.0,
    description:
      "Преобразователь частоты для промышленных машин мощностью 5.5 кВт. Особенности: простая настройка, встроенная связь Modbus, энергосберегающие алгоритмы. Подходит для насосов, вентиляторов и конвейерных применений со степенью защиты IP20.",
    images: [
      "https://images.unsplash.com/photo-1581092335871-5d9e0c2d0a3b",
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
    ],
    productCode: "ATV320U55N4B",
    datasheet: "https://www.schneider-electric.com/atv320-datasheet.pdf",
    seo: {
      title: "Schneider Altivar 320 VFD | Преобразователь частоты 5.5 кВт",
      description:
        "Преобразователь частоты с встроенной связью Modbus для промышленных машин, включая насосы, вентиляторы и конвейеры.",
      keywords: [
        "ПЧ",
        "Schneider Electric",
        "Altivar",
        "ATV320U55N4B",
        "преобразователь частоты",
        "управление двигателем",
      ],
    },
  },
  {
    id: "HMI_003",
    condition: "Used",
    onStock: true,
    onStockQuantity: 2,
    previewImageUrl:
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
    previewImageAlt: "Сенсорная панель Siemens HMI",
    brand: "Siemens",
    name: "SIMATIC HMI TP700 Comfort Panel",
    deliveryTime: 4,
    price: 1890.75,
    description:
      "Восстановленная 7-дюймовая сенсорная панель HMI с широкоэкранным дисплеем высокого разрешения. Особенности: интерфейс PROFINET, встроенная системная диагностика, включена лицензия на проект. Поставляется с годовой гарантией и заводским сбросом с последней версией прошивки.",
    images: [
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
      "https://images.unsplash.com/photo-1581091226033-d5c48150dbaa",
    ],
    productCode: "6AV2124-0GC13-0AX0",
    datasheet: "https://www.siemens.com/tp700-comfort-datasheet.pdf",
    seo: {
      title:
        "Siemens SIMATIC HMI TP700 | Восстановленная промышленная сенсорная панель",
      description:
        "Восстановленная 7-дюймовая сенсорная панель HMI с интерфейсом PROFINET, встроенной диагностикой и годовой гарантией.",
      keywords: [
        "HMI",
        "Siemens",
        "сенсорная панель",
        "6AV2124-0GC13-0AX0",
        "восстановленная HMI",
        "промышленный дисплей",
      ],
    },
  },
  {
    id: "SEN_004",
    condition: "New",
    onStock: false,
    onStockQuantity: 0,
    previewImageUrl:
      "https://images.unsplash.com/photo-1581091226033-d5c48150dbaa",
    previewImageAlt: "Индуктивный датчик приближения",
    brand: "SICK",
    name: "Индуктивный датчик приближения IME series",
    deliveryTime: 7,
    price: 89.95,
    description:
      "Индуктивный датчик приближения с резьбовым корпусом M12. Дальность срабатывания 4 мм, выход PNP нормально разомкнутый, степень защиты IP68. Особенности: светодиодный индикатор состояния, защита от короткого замыкания, расширенный температурный диапазон от -25°C до +75°C.",
    images: ["https://images.unsplash.com/photo-1581091226033-d5c48150dbaa"],
    productCode: "IME12-04NPSZW2S",
    datasheet: "https://www.sick.com/ime-series-datasheet.pdf",
    seo: {
      title:
        "SICK IME Индуктивный датчик приближения | M12 Промышленный датчик",
      description:
        "Индуктивный датчик приближения с дальностью срабатывания 4 мм, выходом PNP и степенью защиты IP68 для суровых промышленных условий.",
      keywords: [
        "датчик приближения",
        "SICK",
        "IME12-04NPSZW2S",
        "индуктивный датчик",
        "промышленный датчик",
        "датчик M12",
      ],
    },
  },
  {
    id: "MOT_005",
    condition: "New",
    onStock: true,
    onStockQuantity: 25,
    previewImageUrl:
      "https://images.unsplash.com/photo-1581092335871-5d9e0c2d0a3b",
    previewImageAlt: "Электродвигатель ABB",
    brand: "ABB",
    name: "Электродвигатель IE3 - 7.5kW",
    deliveryTime: 10,
    price: 875.3,
    description:
      "Асинхронный двигатель переменного тока с повышенной эффективностью IE3 мощностью 7.5 кВт. Особенности: 4-полюсное исполнение, монтаж на лапах B3, степень защиты IP55. Подходит для насосов, вентиляторов, компрессоров и общепромышленных применений с номинальным напряжением 400В.",
    images: [
      "https://images.unsplash.com/photo-1581092335871-5d9e0c2d0a3b",
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
    ],
    productCode: "M3BP160MLC4",
    datasheet: "https://www.abb.com/ie3-motor-7-5kw-datasheet.pdf",
    seo: {
      title:
        "ABB IE3 Электродвигатель | 7.5 кВт Двигатель повышенной эффективности",
      description:
        "Электродвигатель IE3 мощностью 7.5 кВт с повышенной эффективностью и степенью защиты IP55 для насосов, вентиляторов, компрессоров и промышленных применений.",
      keywords: [
        "электродвигатель",
        "ABB",
        "M3BP160MLC4",
        "двигатель IE3",
        "промышленный двигатель",
        "AC двигатель",
      ],
    },
  },
  {
    id: "CNT_006",
    condition: "Used",
    onStock: true,
    onStockQuantity: 1,
    previewImageUrl:
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
    previewImageAlt: "Контроллер Allen Bradley PLC",
    brand: "Rockwell Automation",
    name: "ControlLogix 5570 Controller",
    deliveryTime: 5,
    price: 3250.0,
    description:
      "Восстановленный контроллер ControlLogix с пользовательской памятью 2 МБ. Включает модуль связи Ethernet/IP и годовую гарантию. Поддерживает до 128 000 цифровых входов/выходов и 4 000 аналоговых. Заводской сброс с последней версией прошивки.",
    images: [
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
      "https://images.unsplash.com/photo-1581091226033-d5c48150dbaa",
    ],
    productCode: "1756-L71",
    datasheet:
      "https://www.rockwellautomation.com/controllogix5570-datasheet.pdf",
    seo: {
      title: "Rockwell ControlLogix 5570 | Восстановленный промышленный ПЛК",
      description:
        "Восстановленный ПЛК ControlLogix с памятью 2 МБ, поддержкой Ethernet/IP и годовой гарантией для промышленной автоматизации.",
      keywords: [
        "ПЛК",
        "Rockwell Automation",
        "ControlLogix",
        "1756-L71",
        "восстановленный ПЛК",
        "промышленный контроллер",
      ],
    },
  },
  {
    id: "PWR_007",
    condition: "New",
    onStock: true,
    onStockQuantity: 12,
    previewImageUrl:
      "https://images.unsplash.com/photo-1581091226033-d5c48150dbaa",
    previewImageAlt: "Блок питания Siemens",
    brand: "Siemens",
    name: "SITOP PSU100S 20A Блок питания",
    deliveryTime: 2,
    price: 245.8,
    description:
      "Блок питания для DIN-рейки с выходным током 20 А при напряжении 24 В постоянного тока. Особенности: широкий диапазон входного напряжения (85-264 В переменного тока), высокий КПД до 90%, защита от короткого замыкания. Включает светодиодный индикатор состояния и рабочий температурный диапазон от -25°C до +70°C.",
    images: ["https://images.unsplash.com/photo-1581091226033-d5c48150dbaa"],
    productCode: "6EP1336-3BA10",
    datasheet: "https://www.siemens.com/sitop-psu100s-datasheet.pdf",
    seo: {
      title: "Siemens SITOP PSU100S | 20A Промышленный блок питания",
      description:
        "Блок питания для DIN-рейки на 24 В с выходным током 20 А, высоким КПД и широким температурным диапазоном для промышленных систем автоматизации.",
      keywords: [
        "блок питания",
        "Siemens",
        "SITOP",
        "6EP1336-3BA10",
        "DIN-рейка блок питания",
        "промышленное питание",
      ],
    },
  },
  {
    id: "RBT_008",
    condition: "New",
    onStock: false,
    onStockQuantity: 0,
    previewImageUrl:
      "https://images.unsplash.com/photo-1581092335871-5d9e0c2d0a3b",
    previewImageAlt: "Промышленный робот Fanuc",
    brand: "Fanuc",
    name: "LR Mate 200iD Промышленный робот",
    deliveryTime: 30,
    price: 28500.0,
    description:
      "Компактный 6-осевой промышленный робот с грузоподъемностью 7 кг и вылетом 717 мм. Особенности: высокоскоростная работа, встроенная возможность машинного зрения, тонкий дизайн для ограниченного пространства. Идеально подходит для обслуживания станков, комплектации, упаковки и сборочных применений.",
    images: [
      "https://images.unsplash.com/photo-1581092335871-5d9e0c2d0a3b",
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
      "https://images.unsplash.com/photo-1581091226033-d5c48150dbaa",
    ],
    productCode: "LR-200ID-7C",
    datasheet: "https://www.fanuc.com/lr-mate-200id-datasheet.pdf",
    seo: {
      title: "Fanuc LR Mate 200iD | Компактный 6-осевой промышленный робот",
      description:
        "Компактный 6-осевой промышленный робот с грузоподъемностью 7 кг для обслуживания станков, комплектации и сборочных применений в ограниченном пространстве.",
      keywords: [
        "промышленный робот",
        "Fanuc",
        "LR-200ID-7C",
        "LR Mate",
        "роботизированная рука",
        "робот автоматизации",
      ],
    },
  },
  {
    id: "SWT_009",
    condition: "Used",
    onStock: true,
    onStockQuantity: 3,
    previewImageUrl:
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
    previewImageAlt: "Промышленный коммутатор Cisco",
    brand: "Cisco",
    name: "IE-2000 Промышленный коммутатор",
    deliveryTime: 3,
    price: 1875.4,
    description:
      "Восстановленный 8-портовый промышленный управляемый коммутатор с поддержкой PoE. Особенности: расширенный температурный диапазон (-40°C до +75°C), резервированный вход питания, промышленная надежность. Включает программное обеспечение Cisco IOS с расширенными функциями безопасности.",
    images: ["https://images.unsplash.com/photo-1581092160562-40aa08e78837"],
    productCode: "IE-2000-8TC",
    datasheet: "https://www.cisco.com/ie-2000-datasheet.pdf",
    seo: {
      title:
        "Cisco IE-2000 Промышленный коммутатор | Восстановленный управляемый коммутатор Ethernet",
      description:
        "Восстановленный 8-портовый промышленный управляемый коммутатор с PoE, расширенным температурным диапазоном и расширенной безопасностью для суровых условий эксплуатации.",
      keywords: [
        "промышленный коммутатор",
        "Cisco",
        "IE-2000-8TC",
        "коммутатор Ethernet",
        "управляемый коммутатор",
        "PoE коммутатор",
      ],
    },
  },
  {
    id: "SCA_010",
    condition: "New",
    onStock: true,
    onStockQuantity: 6,
    previewImageUrl:
      "https://images.unsplash.com/photo-1581091226033-d5c48150dbaa",
    previewImageAlt: "SCADA система Siemens",
    brand: "Siemens",
    name: "SIMATIC WinCC SCADA v8.0",
    deliveryTime: 1,
    price: 4560.0,
    description:
      "SCADA система с 2048 тегами для визуализации и мониторинга процессов. Включает встроенное архивирование, инструменты отчетности и веб-операции. Поддерживает несколько протоколов связи, включая OPC UA, Modbus TCP/IP и связь Siemens S7.",
    images: [
      "https://images.unsplash.com/photo-1581091226033-d5c48150dbaa",
      "https://images.unsplash.com/photo-1581092335871-5d9e0c2d0a3b",
    ],
    productCode: "6AV6381-2BH07-0AV0",
    datasheet: "https://www.siemens.com/wincc-v8-datasheet.pdf",
    seo: {
      title:
        "Siemens SIMATIC WinCC v8.0 | Промышленное SCADA программное обеспечение",
      description:
        "SCADA программное обеспечение с 2048 тегами, архивированием, отчетностью и веб-операцией для промышленного мониторинга и управления процессами.",
      keywords: [
        "SCADA",
        "Siemens",
        "WinCC",
        "6AV6381-2BH07-0AV0",
        "промышленное ПО",
        "управление процессами",
      ],
    },
  },
]

export const api = {
  async getProductList(): Promise<ProductBackend[]> {
    await new Promise((res) => setTimeout(res, 1000))
    return productsList
  },
  async getProductDetail(id: string): Promise<ProductDetailBackend | null> {
    await new Promise((res) => setTimeout(res, 1000))
    return ProductsDetailList.find((product) => product.id === id) || null
  },
}
